[package]
name = "glcl"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
parse_link_header = "0.3.3"
reqwest = { version = "0.12.5", features = ["json"] }
serde = { version = "1.0.205", features = ["derive"] }
tokio = { version = "1.39.2", features = ["full"] }
